spring.application.name=genrag

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/genrag
spring.datasource.username=${DB_USER:genrag}
spring.datasource.password=${DB_PASSWORD:genrag}
spring.jpa.hibernate.ddl-auto=validate

# DB connection timeout for 10 seconds
spring.datasource.hikari.initialization-fail-timeout=10000

# For development only
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

# JWT related info
genrag.jwt.access-secret=${JWT_ACCESS_TOKEN_SECRET}
genrag.jwt.refresh-secret=${JWT_REFRESH_TOKEN_SECRET}
genrag.jwt.access-ttl=15m
genrag.jwt.refresh-ttl=30d

# Cookies related info
genrag.auth.cookie.secure=${COOKIE_SECURE:true}

# Frontend URL
genrag.frontend.url=${FRONTEND_URL:http://localhost:5173}

# To read teh X-Forwarded-For header sent by frontend proxy
server.forward-headers-strategy=framework
